### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by claire-kz** [veechau/EventRight#1]
- Remove all references to FresherNote and notes. 
- Each feature in the MVP has the exact same bullet points.  Provide unique descriptions of each feature so it is clear what purpose they serve.
- Styling should not be its own phase.  It should be done as features are development.  An individual phase is not considered complete until it has sufficient styling. 
- Phases 1 through 3 looks good, after that needs some revising.  Where is the phase for registration and tickets?  It's listed second in the MVP but does not appear on the timeline.  What about a user dashboard?  It will have to contain info on both the events you've created and one's for which you've purchased tickets.

**Comment by veechau** [comment]
- Revised time estimates for phase 1 and phase 2
- Included tickets and user landing page as phases 4 and 5
- Incorporated styling into each phase to style as features are built
