### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by claire-kz** [veechau/EventRight#2]
- User and session should be nested under api namespace.  We require front-end auth and single-page apps. 
- Why is there a notebooks api?
- Why is bookmarks listed twice?  Neither contains routes that would hit the `BookmarksController`.  Needs to be fixed.  
- Avoid deeply nested routes - favor passing params in request

**Comment by veechau** [comment]
- Nested user and session under api namespace
- Updated routes with correct names
- Changed Bookmark and Ticket routes to pass in current user and event data through params
